In [1]:
import pandas as pd

In [2]:
support_tickets = pd.read_csv("./dataset/support_tickets.csv")
transactions = pd.read_csv("./dataset/transactions.csv")

In [3]:
support_tickets

,ticket_id,date_created,customer_id,channel,category,sub_category,query_text,sentiment,risk_level,resolution_text,resolution_time_minutes,resolved_by,customer_satisfaction,escalated
0,TKT-10001,2023-03-13,CUST872246,Web Chat,Fraud/Unauthorized,I see a transaction of ₹999 I didn't m,I see a transaction of ₹999 I didn't make on 2...,Urgent,High,Unauthorized transaction reported on account. ...,28,Sneha R.,2,Yes
1,TKT-10002,2023-11-05,CUST127824,Branch,Fraud/Unauthorized,I see a transaction of ₹500 I didn't m,I see a transaction of ₹500 I didn't make on 1...,Neutral,High,Unauthorized transaction reported on account. ...,27,Auto-Resolved,5,No
2,TKT-10003,2023-08-05,CUST456778,Phone,Fraud/Unauthorized,I see a transaction of ₹25000 I didn't m,"I see a transaction of ₹25,000 I didn't make o...",Neutral,High,Unauthorized transaction reported on account. ...,11,Anjali K.,2,No
3,TKT-10004,2023-01-23,CUST865179,Email,Fraud/Unauthorized,I see a transaction of ₹999 I didn't m,I see a transaction of ₹999 I didn't make on 1...,Confused,High,Unauthorized transaction reported on account. ...,8,Vikram P.,2,Yes
4,TKT-10005,2023-12-05,CUST338968,Phone,Fraud/Unauthorized,I see a transaction of ₹25000 I didn't m,"I see a transaction of ₹25,000 I didn't make o...",Frustrated,High,Unauthorized transaction reported on account. ...,12,Priya S.,5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,TKT-10196,2023-07-22,CUST958130,Phone,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Neutral,Low,App sync issue identified. Cache cleared from ...,104,Priya S.,4,No
196,TKT-10197,2023-04-20,CUST311883,Branch,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Anxious,Low,App sync issue identified. Cache cleared from ...,173,Auto-Resolved,4,No
197,TKT-10198,2023-05-05,CUST153231,Branch,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Neutral,Low,App sync issue identified. Cache cleared from ...,193,Rahul M.,3,No
198,TKT-10199,2023-12-15,CUST908206,Mobile App,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Frustrated,Low,App sync issue identified. Cache cleared from ...,170,Rahul M.,4,No
199,TKT-10200,2023-05-27,CUST777273,Web Chat,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Frustrated,Low,App sync issue identified. Cache cleared from ...,196,Sneha R.,3,No

In [4]:
transactions

,transaction_id,account_id,timestamp,amount_inr,merchant_name,merchant_category,transaction_type,city,hour_of_day,day_of_week,is_international,velocity_flag,geo_anomaly_flag,high_amount_flag,fraud_label,fraud_reason
0,TXN500001,ACC995993,2023-05-21 01:35:00,7553.61,Flipkart,E-commerce,Credit Card,Mumbai,1,Sunday,No,No,No,No,0,Not applicable
1,TXN500002,ACC163182,2023-09-26 10:44:00,634.78,Zomato,Food Delivery,Credit Card,Chennai,10,Tuesday,No,No,No,No,0,Not applicable
2,TXN500003,ACC107161,2023-08-26 01:35:00,1136.71,Zomato,Food Delivery,UPI,Hyderabad,1,Saturday,No,No,No,No,0,Not applicable
3,TXN500004,ACC103642,2023-07-09 02:34:00,41478.01,VPN_Service_Anon,Digital,UPI,Dubai,2,Sunday,Yes,Yes,Yes,Yes,1,Off-hours
4,TXN500005,ACC218118,2023-04-07 18:46:00,1139.76,Ola Cabs,Transport,Debit Card,Chennai,18,Friday,No,No,No,No,0,Not applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,TXN501996,ACC535604,2023-02-26 04:52:00,7815.03,Ola Cabs,Transport,Debit Card,Ahmedabad,4,Sunday,No,No,No,No,0,Not applicable
1996,TXN501997,ACC536045,2023-06-13 22:01:00,1566.37,Flipkart,E-commerce,Debit Card,Delhi,22,Tuesday,No,No,No,No,0,Not applicable
1997,TXN501998,ACC645617,2023-08-12 21:23:00,13608.73,MakeMyTrip,Travel,Credit Card,Mumbai,21,Saturday,No,No,No,No,0,Not applicable
1998,TXN501999,ACC133782,2023-10-18 14:54:00,317.03,MakeMyTrip,Travel,UPI,Ahmedabad,14,Wednesday,No,No,No,No,0,Not applicable
1999,TXN502000,ACC876513,2023-03-10 02:18:00,1689.71,PhonePe Wallet,Wallet,Net Banking,Chennai,2,Friday,No,No,No,No,0,Not applicable

In [5]:
import json

with open("./dataset/qa_pairs.json", "r") as f:
    data = json.load(f)

print(json.dumps(data, indent=4))

[
    {
        "id": "QA001",
        "category": "Fraud",
        "question": "I noticed an unauthorized transaction of \u20b915,000 on my account. What should I do?",
        "answer": "Please report immediately via our 24x7 helpline or mobile app. We will block your card, raise a dispute, and if reported within 3 working days, you have zero liability under RBI guidelines. A provisional credit will be issued within 10 working days.",
        "policy_ref": "Fraud Handling Policy \u00a73, \u00a74",
        "risk_level": "High",
        "suggested_action": "Block card, raise dispute, escalate to fraud team"
    },
    {
        "id": "QA002",
        "category": "Fraud",
        "question": "How long does fraud investigation take?",
        "answer": "Fraud investigations are completed within 30-45 working days. You will receive updates every 7 days. A provisional credit may be applied within 10 working days for eligible cases.",
        "policy_ref": "Fraud Handling Policy \u00a74",
        "risk_level": "Medium",
        "suggested_action": "Update customer with reference number"
    },
    {
        "id": "QA003",
        "category": "Fraud",
        "question": "Someone used my OTP to transfer money. Can I get a refund?",
        "answer": "If the OTP was shared voluntarily, liability may apply per RBI guidelines. If it was obtained through phishing/vishing, report immediately. Our fraud team will investigate. Account access will be suspended immediately for safety.",
        "policy_ref": "Fraud Handling Policy \u00a73.2, \u00a76",
        "risk_level": "High",
        "suggested_action": "Suspend account access, escalate to fraud team, advise FIR"
    },
    {
        "id": "QA004",
        "category": "Fraud",
        "question": "Multiple small transactions are showing up that I didn't make",
        "answer": "Multiple micro-transactions could indicate card skimming or credential compromise. Your card will be blocked immediately. A new card will be dispatched and a police complaint (FIR) will be filed on your behalf. Please do not use existing card.",
        "policy_ref": "Fraud Handling Policy \u00a75 High Risk",
        "risk_level": "High",
        "suggested_action": "Block card, dispatch new card, file FIR"
    },
    {
        "id": "QA005",
        "category": "Fraud",
        "question": "I received an OTP I didn't request. Is my account safe?",
        "answer": "An unrequested OTP could indicate a fraud attempt or SIM swap. Your account has been placed under temporary hold. Please change your mobile banking PIN immediately and visit the nearest branch with ID proof.",
        "policy_ref": "Fraud Handling Policy \u00a75, \u00a76.2",
        "risk_level": "High",
        "suggested_action": "Suspend account, advise branch visit, reset credentials"
    },
    {
        "id": "QA006",
        "category": "Loan",
        "question": "What is the minimum CIBIL score required for a personal loan?",
        "answer": "The minimum CIBIL score for a personal loan is 720. A higher score may qualify you for better interest rates ranging from 10.5% to 18% p.a. If your score is below 720, we recommend clearing existing dues and reapplying after 6 months.",
        "policy_ref": "Loan Processing Policy \u00a72.2",
        "risk_level": "Low",
        "suggested_action": "Share eligibility criteria, suggest credit improvement steps"
    },
    {
        "id": "QA007",
        "category": "Loan",
        "question": "How long will my home loan take to get approved?",
        "answer": "Home loan processing takes 15-21 working days after complete document submission. This includes legal verification of property documents, technical appraisal, and credit assessment. Pre-approved customers may receive faster processing.",
        "policy_ref": "Loan Processing Policy \u00a74.3",
        "risk_level": "Low",
        "suggested_action": "Share document checklist, set timeline expectation"
    },
    {
        "id": "QA008",
        "category": "Loan",
        "question": "Can I foreclose my floating rate home loan without charges?",
        "answer": "Yes. As per RBI guidelines, there are no foreclosure charges on floating rate home loans. You only need to pay the outstanding principal plus accrued interest up to the foreclosure date. A no-dues certificate will be issued within 7 working days.",
        "policy_ref": "Loan Processing Policy \u00a77.1",
        "risk_level": "Low",
        "suggested_action": "Calculate outstanding amount, process foreclosure request"
    },
    {
        "id": "QA009",
        "category": "Loan",
        "question": "My loan application was rejected. What can I do?",
        "answer": "A rejection letter with specific reasons will be issued within 3 working days. Common reasons include low credit score, insufficient income, or document deficiency. Based on the reason, we can guide you on adding a co-applicant, improving your credit profile, or reapplying for a lower amount.",
        "policy_ref": "Loan Processing Policy \u00a76",
        "risk_level": "Low",
        "suggested_action": "Share rejection reasons, provide improvement guidance"
    },
    {
        "id": "QA010",
        "category": "Loan",
        "question": "I lost my job. Can I pause my loan EMIs?",
        "answer": "Yes, we have EMI moratorium options. We can evaluate a restructuring request under RBI guidelines. Please visit your nearest branch with employment separation letter. An EMI holiday of up to 3 months may be granted with interest capitalized during the period.",
        "policy_ref": "Loan Processing Policy \u2014 Restructuring clause",
        "risk_level": "High",
        "suggested_action": "Initiate restructuring request, connect to relationship manager"
    },
    {
        "id": "QA011",
        "category": "KYC",
        "question": "Why is my account restricted? I submitted KYC documents last week.",
        "answer": "Documents may be pending verification (typically 48 hours). If submitted online, please also confirm via the branch. If restrictions persist beyond 48 hours, please call our helpline with your complaint reference number for priority processing.",
        "policy_ref": "KYC Policy \u00a76.1",
        "risk_level": "Medium",
        "suggested_action": "Check document status, escalate if pending > 48 hours"
    },
    {
        "id": "QA012",
        "category": "KYC",
        "question": "My Aadhaar name and bank name don't match. How do I fix this?",
        "answer": "A name mismatch requires physical branch visit. Please bring a gazette notification or court affidavit for name correction. Alternatively, submit a written request with supporting documents. The update will be processed within 5 working days.",
        "policy_ref": "KYC Policy \u00a72.1",
        "risk_level": "Medium",
        "suggested_action": "Guide to branch, request gazette notification or affidavit"
    },
    {
        "id": "QA013",
        "category": "KYC",
        "question": "What documents do I need for KYC?",
        "answer": "For individuals: Aadhaar card (mandatory), PAN card (for transactions above \u20b950,000), and a recent photograph. For enhanced accounts, additional address proof may be required. NRI customers need a valid passport and overseas address proof.",
        "policy_ref": "KYC Policy \u00a72.1",
        "risk_level": "Low",
        "suggested_action": "Share document checklist based on account type"
    },
    {
        "id": "QA014",
        "category": "KYC",
        "question": "How often do I need to update my KYC?",
        "answer": "KYC refresh frequency depends on your risk category: High-risk customers every 2 years, Medium-risk every 8 years, Low-risk every 10 years. NRI accounts require annual review. You will receive an advance notification before your KYC expires.",
        "policy_ref": "KYC Policy \u00a74",
        "risk_level": "Low",
        "suggested_action": "Share KYC review schedule, send reminder"
    },
    {
        "id": "QA015",
        "category": "Account Access",
        "question": "I'm locked out of my net banking. How do I regain access?",
        "answer": "Net banking access is temporarily suspended after 3 failed login attempts. You can reset access by: (1) Generating new IPIN at ATM, (2) Calling our IVR helpline, or (3) Visiting nearest branch with ID proof. Access is restored immediately upon successful PIN reset.",
        "policy_ref": "Account Access Policy",
        "risk_level": "Low",
        "suggested_action": "Guide through IPIN reset steps"
    },
    {
        "id": "QA016",
        "category": "Account Access",
        "question": "My salary hasn't been credited even though it's the 5th",
        "answer": "Salary delays may be due to employer's payroll batch timing or bank holidays. Please check with your HR/payroll team first. If the employer has processed payment but amount not credited by EOD, raise a complaint and we will trace the NEFT/RTGS transaction.",
        "policy_ref": "Standard account operations",
        "risk_level": "Low",
        "suggested_action": "Advise HR check first, trace NEFT if needed"
    },
    {
        "id": "QA017",
        "category": "Fraud",
        "question": "I got a call from someone claiming to be from the bank asking for my CVV",
        "answer": "This is a vishing (voice phishing) attempt. Our bank NEVER asks for CVV, OTP, or PIN over phone or email. Do not share any information. Report this number to our fraud helpline immediately. Your account will be monitored for unusual activity.",
        "policy_ref": "Fraud Handling Policy \u00a78.4",
        "risk_level": "High",
        "suggested_action": "Alert fraud monitoring, log caller number, advise customer"
    },
    {
        "id": "QA018",
        "category": "Account Access",
        "question": "Can I open a joint account with my spouse?",
        "answer": "Yes. Both account holders must visit the branch with PAN, Aadhaar, and passport-size photographs. You can choose the operational mode: Either or Survivor (most common), Former or Survivor, or Jointly. The process takes 1-2 working days.",
        "policy_ref": "Account Opening Policy",
        "risk_level": "Low",
        "suggested_action": "Guide to branch with checklist"
    },
    {
        "id": "QA019",
        "category": "Loan",
        "question": "What is the maximum education loan I can get for studying abroad?",
        "answer": "Education loans for overseas studies are available up to \u20b940 lakh. A moratorium applies during the study period plus 6 months after course completion. Interest rates range from 8.5% to 12% p.a. Eligible courses include those at recognized universities abroad with admission proof.",
        "policy_ref": "Loan Processing Policy \u00a71.4",
        "risk_level": "Low",
        "suggested_action": "Share application checklist, connect to education loan specialist"
    },
    {
        "id": "QA020",
        "category": "KYC",
        "question": "My video KYC keeps failing. What should I do?",
        "answer": "V-CIP failures are often due to poor lighting, internet connectivity, or document quality. Try: (1) Use a well-lit area, (2) Ensure stable 4G/WiFi connection, (3) Keep Aadhaar clearly visible. If issues persist, a fresh V-CIP link will be sent, or visit branch for physical KYC.",
        "policy_ref": "KYC Policy \u00a75",
        "risk_level": "Low",
        "suggested_action": "Re-send V-CIP link, suggest branch as fallback"
    }
]

In [6]:
support_tickets.isna().sum(), "-----------------------------", transactions.isna().sum()

(ticket_id                  0
 date_created               0
 customer_id                0
 channel                    0
 category                   0
 sub_category               0
 query_text                 0
 sentiment                  0
 risk_level                 0
 resolution_text            0
 resolution_time_minutes    0
 resolved_by                0
 customer_satisfaction      0
 escalated                  0
 dtype: int64,
 '-----------------------------',
 transaction_id       0
 account_id           0
 timestamp            0
 amount_inr           0
 merchant_name        0
 merchant_category    0
 transaction_type     0
 city                 0
 hour_of_day          0
 day_of_week          0
 is_international     0
 velocity_flag        0
 geo_anomaly_flag     0
 high_amount_flag     0
 fraud_label          0
 fraud_reason         0
 dtype: int64)

In [7]:
support_tickets.head(20)

,ticket_id,date_created,customer_id,channel,category,sub_category,query_text,sentiment,risk_level,resolution_text,resolution_time_minutes,resolved_by,customer_satisfaction,escalated
0,TKT-10001,2023-03-13,CUST872246,Web Chat,Fraud/Unauthorized,I see a transaction of ₹999 I didn't m,I see a transaction of ₹999 I didn't make on 2...,Urgent,High,Unauthorized transaction reported on account. ...,28,Sneha R.,2,Yes
1,TKT-10002,2023-11-05,CUST127824,Branch,Fraud/Unauthorized,I see a transaction of ₹500 I didn't m,I see a transaction of ₹500 I didn't make on 1...,Neutral,High,Unauthorized transaction reported on account. ...,27,Auto-Resolved,5,No
2,TKT-10003,2023-08-05,CUST456778,Phone,Fraud/Unauthorized,I see a transaction of ₹25000 I didn't m,"I see a transaction of ₹25,000 I didn't make o...",Neutral,High,Unauthorized transaction reported on account. ...,11,Anjali K.,2,No
3,TKT-10004,2023-01-23,CUST865179,Email,Fraud/Unauthorized,I see a transaction of ₹999 I didn't m,I see a transaction of ₹999 I didn't make on 1...,Confused,High,Unauthorized transaction reported on account. ...,8,Vikram P.,2,Yes
4,TKT-10005,2023-12-05,CUST338968,Phone,Fraud/Unauthorized,I see a transaction of ₹25000 I didn't m,"I see a transaction of ₹25,000 I didn't make o...",Frustrated,High,Unauthorized transaction reported on account. ...,12,Priya S.,5,No
5,TKT-10006,2023-05-17,CUST835911,Web Chat,Fraud/Unauthorized,There's an ATM withdrawal of ₹5000 from,"There's an ATM withdrawal of ₹5,000 from Banga...",Confused,High,Location mismatch confirmed. ATM transaction f...,25,Rahul M.,3,No
6,TKT-10007,2023-12-17,CUST440035,Web Chat,Fraud/Unauthorized,There's an ATM withdrawal of ₹7500 from,"There's an ATM withdrawal of ₹7,500 from Hyder...",Neutral,High,Location mismatch confirmed. ATM transaction f...,6,Anjali K.,5,No
7,TKT-10008,2023-12-02,CUST623481,Email,Fraud/Unauthorized,There's an ATM withdrawal of ₹2000 from,"There's an ATM withdrawal of ₹2,000 from Hyder...",Urgent,High,Location mismatch confirmed. ATM transaction f...,19,Rahul M.,4,No
8,TKT-10009,2023-10-26,CUST518801,Phone,Fraud/Unauthorized,There's an ATM withdrawal of ₹15000 from,"There's an ATM withdrawal of ₹15,000 from Hyde...",Neutral,High,Location mismatch confirmed. ATM transaction f...,9,Sneha R.,5,No
9,TKT-10010,2023-08-05,CUST725380,Web Chat,Fraud/Unauthorized,There's an ATM withdrawal of ₹500 from,There's an ATM withdrawal of ₹500 from Hyderab...,Angry,High,Location mismatch confirmed. ATM transaction f...,17,Sneha R.,5,Yes
10,TKT-10011,2023-10-02,CUST887352,Phone,Fraud/Unauthorized,I received an OTP but never requested it,I received an OTP but never requested it,Urgent,High,OTP triggered without user action — possible p...,15,Priya S.,4,Yes
11,TKT-10012,2023-04-02,CUST632342,Web Chat,Fraud/Unauthorized,I received an OTP but never requested it,I received an OTP but never requested it,Urgent,High,OTP triggered without user action — possible p...,14,Auto-Resolved,3,No
12,TKT-10013,2023-06-15,CUST612340,Web Chat,Fraud/Unauthorized,I received an OTP but never requested it,I received an OTP but never requested it,Frustrated,High,OTP triggered without user action — possible p...,16,Anjali K.,3,No
13,TKT-10014,2023-09-30,CUST903035,Mobile App,Fraud/Unauthorized,I received an OTP but never requested it,I received an OTP but never requested it,Neutral,High,OTP triggered without user action — possible p...,26,Vikram P.,3,No
14,TKT-10015,2023-06-09,CUST518373,Phone,Fraud/Unauthorized,I received an OTP but never requested it,I received an OTP but never requested it,Angry,High,OTP triggered without user action — possible p...,21,Vikram P.,2,No
15,TKT-10016,2023-10-29,CUST330914,Web Chat,Fraud/Unauthorized,My card was charged ₹999 by an unknown,My card was charged ₹999 by an unknown merchant,Frustrated,Medium,Merchant identified as third-party aggregator....,22,Rahul M.,3,No
16,TKT-10017,2023-12-09,CUST608993,Mobile App,Fraud/Unauthorized,My card was charged ₹500 by an unknown,My card was charged ₹500 by an unknown merchant,Confused,Medium,Merchant identified as third-party aggregator....,31,Auto-Resolved,5,No
17,TKT-10018,2023-02-18,CUST201639,Email,Fraud/Unauthorized,My card was charged ₹25000 by an unknown,"My card was charged ₹25,000 by an unknown merc...",Anxious,Medium,Merchant identified as third-party aggregator....,69,Vikram P.,4,No
18,TKT-10019,2023-07-26,CUST863587,Phone,Fraud/Unauthorized,My card was charged ₹500 by an unknown,My card was charged ₹500 by an unknown merchant,Frustrated,Medium,Merchant identified as third-party aggregator....,46,Rahul M.,3,No
19,TKT-10020,2023-08-25,CUST361941,Web Chat,Fraud/Unauthorized,My card was charged ₹15000 by an unknown,"My card was charged ₹15,000 by an unknown merc...",Angry,Medium,Merchant identified as third-party aggregator....,85,Priya S.,3,No

In [8]:
st_cols = support_tickets.columns

for col in st_cols:
    print("--------------------------------------------")
    print(f"Column: {col}")
    print(support_tickets[col].unique())
    print()

--------------------------------------------
Column: ticket_id
['TKT-10001' 'TKT-10002' 'TKT-10003' 'TKT-10004' 'TKT-10005' 'TKT-10006'
 'TKT-10007' 'TKT-10008' 'TKT-10009' 'TKT-10010' 'TKT-10011' 'TKT-10012'
 'TKT-10013' 'TKT-10014' 'TKT-10015' 'TKT-10016' 'TKT-10017' 'TKT-10018'
 'TKT-10019' 'TKT-10020' 'TKT-10021' 'TKT-10022' 'TKT-10023' 'TKT-10024'
 'TKT-10025' 'TKT-10026' 'TKT-10027' 'TKT-10028' 'TKT-10029' 'TKT-10030'
 'TKT-10031' 'TKT-10032' 'TKT-10033' 'TKT-10034' 'TKT-10035' 'TKT-10036'
 'TKT-10037' 'TKT-10038' 'TKT-10039' 'TKT-10040' 'TKT-10041' 'TKT-10042'
 'TKT-10043' 'TKT-10044' 'TKT-10045' 'TKT-10046' 'TKT-10047' 'TKT-10048'
 'TKT-10049' 'TKT-10050' 'TKT-10051' 'TKT-10052' 'TKT-10053' 'TKT-10054'
 'TKT-10055' 'TKT-10056' 'TKT-10057' 'TKT-10058' 'TKT-10059' 'TKT-10060'
 'TKT-10061' 'TKT-10062' 'TKT-10063' 'TKT-10064' 'TKT-10065' 'TKT-10066'
 'TKT-10067' 'TKT-10068' 'TKT-10069' 'TKT-10070' 'TKT-10071' 'TKT-10072'
 'TKT-10073' 'TKT-10074' 'TKT-10075' 'TKT-10076' 'TKT-10077' 'TKT-10078'
 'TKT-10079' 'TKT-10080' 'TKT-10081' 'TKT-10082' 'TKT-10083' 'TKT-10084'
 'TKT-10085' 'TKT-10086' 'TKT-10087' 'TKT-10088' 'TKT-10089' 'TKT-10090'
 'TKT-10091' 'TKT-10092' 'TKT-10093' 'TKT-10094' 'TKT-10095' 'TKT-10096'
 'TKT-10097' 'TKT-10098' 'TKT-10099' 'TKT-10100' 'TKT-10101' 'TKT-10102'
 'TKT-10103' 'TKT-10104' 'TKT-10105' 'TKT-10106' 'TKT-10107' 'TKT-10108'
 'TKT-10109' 'TKT-10110' 'TKT-10111' 'TKT-10112' 'TKT-10113' 'TKT-10114'
 'TKT-10115' 'TKT-10116' 'TKT-10117' 'TKT-10118' 'TKT-10119' 'TKT-10120'
 'TKT-10121' 'TKT-10122' 'TKT-10123' 'TKT-10124' 'TKT-10125' 'TKT-10126'
 'TKT-10127' 'TKT-10128' 'TKT-10129' 'TKT-10130' 'TKT-10131' 'TKT-10132'
 'TKT-10133' 'TKT-10134' 'TKT-10135' 'TKT-10136' 'TKT-10137' 'TKT-10138'
 'TKT-10139' 'TKT-10140' 'TKT-10141' 'TKT-10142' 'TKT-10143' 'TKT-10144'
 'TKT-10145' 'TKT-10146' 'TKT-10147' 'TKT-10148' 'TKT-10149' 'TKT-10150'
 'TKT-10151' 'TKT-10152' 'TKT-10153' 'TKT-10154' 'TKT-10155' 'TKT-10156'
 'TKT-10157' 'TKT-10158' 'TKT-10159' 'TKT-10160' 'TKT-10161' 'TKT-10162'
 'TKT-10163' 'TKT-10164' 'TKT-10165' 'TKT-10166' 'TKT-10167' 'TKT-10168'
 'TKT-10169' 'TKT-10170' 'TKT-10171' 'TKT-10172' 'TKT-10173' 'TKT-10174'
 'TKT-10175' 'TKT-10176' 'TKT-10177' 'TKT-10178' 'TKT-10179' 'TKT-10180'
 'TKT-10181' 'TKT-10182' 'TKT-10183' 'TKT-10184' 'TKT-10185' 'TKT-10186'
 'TKT-10187' 'TKT-10188' 'TKT-10189' 'TKT-10190' 'TKT-10191' 'TKT-10192'
 'TKT-10193' 'TKT-10194' 'TKT-10195' 'TKT-10196' 'TKT-10197' 'TKT-10198'
 'TKT-10199' 'TKT-10200']

--------------------------------------------
Column: date_created
['2023-03-13' '2023-11-05' '2023-08-05' '2023-01-23' '2023-12-05'
 '2023-05-17' '2023-12-17' '2023-12-02' '2023-10-26' '2023-10-02'
 '2023-04-02' '2023-06-15' '2023-09-30' '2023-06-09' '2023-10-29'
 '2023-12-09' '2023-02-18' '2023-07-26' '2023-08-25' '2023-07-28'
 '2023-06-10' '2023-11-01' '2023-12-03' '2023-11-27' '2023-05-16'
 '2023-12-08' '2023-11-06' '2023-02-08' '2023-12-16' '2023-01-13'
 '2023-04-13' '2023-06-29' '2023-02-25' '2023-05-11' '2023-03-07'
 '2023-01-01' '2023-08-31' '2023-04-12' '2023-12-23' '2023-04-01'
 '2023-08-19' '2023-05-20' '2023-06-19' '2023-01-04' '2023-01-14'
 '2023-06-22' '2023-03-06' '2023-02-28' '2023-07-05' '2023-08-27'
 '2023-11-02' '2023-05-04' '2023-05-05' '2023-12-26' '2023-04-05'
 '2023-04-10' '2023-05-30' '2023-03-18' '2023-04-26' '2023-11-09'
 '2023-03-22' '2023-08-21' '2023-03-05' '2023-08-10' '2023-12-11'
 '2023-08-12' '2023-07-30' '2023-11-17' '2023-01-15' '2023-08-30'
 '2023-08-01' '2023-08-17' '2023-07-16' '2023-01-19' '2023-06-12'
 '2023-08-11' '2023-07-11' '2023-11-14' '2023-01-05' '2023-08-06'
 '2023-10-22' '2023-11-07' '2023-08-14' '2023-10-04' '2023-08-28'
 '2023-12-10' '2023-07-08' '2023-04-19' '2023-04-17' '2023-05-09'
 '2023-01-09' '2023-08-23' '2023-06-14' '2023-09-29' '2023-08-09'
 '2023-12-07' '2023-07-10' '2023-03-21' '2023-08-08' '2023-04-03'
 '2023-11-21' '2023-06-16' '2023-08-15' '2023-02-26' '2023-04-15'
 '2023-03-08' '2023-01-10' '2023-07-27' '2023-03-30' '2023-12-15'
 '2023-10-30' '2023-10-20' '2023-02-13' '2023-06-18' '2023-03-14'
 '2023-07-12' '2023-09-27' '2023-08-13' '2023-05-03' '2023-09-28'
 '2023-02-22' '2023-04-24' '2023-10-08' '2023-11-24' '2023-08-29'
 '2023-11-18' '2023-08-26' '2023-01-22' '2023-07-02' '2023-06-23'
 '2023-05-21' '2023-03-15' '2023-07-18' '2023-03-04' '2023-02-03'
 '2023-09-23' '2023-02-17' '2023-06-13' '2023-10-23' '2023-02-16'
 '2023-12-01' '2023-07-07' '2023-10-13' '2023-10-31' '2023-04-27'
 '2023-12-27' '2023-07-22' '2023-04-20' '2023-05-27']

--------------------------------------------
Column: customer_id
['CUST872246' 'CUST127824' 'CUST456778' 'CUST865179' 'CUST338968'
 'CUST835911' 'CUST440035' 'CUST623481' 'CUST518801' 'CUST725380'
 'CUST887352' 'CUST632342' 'CUST612340' 'CUST903035' 'CUST518373'
 'CUST330914' 'CUST608993' 'CUST201639' 'CUST863587' 'CUST361941'
 'CUST609231' 'CUST830429' 'CUST159942' 'CUST171262' 'CUST712024'
 'CUST414569' 'CUST238890' 'CUST956795' 'CUST320861' 'CUST103717'
 'CUST824586' 'CUST361650' 'CUST288073' 'CUST956253' 'CUST772642'
 'CUST725550' 'CUST146542' 'CUST795612' 'CUST301158' 'CUST418635'
 'CUST932291' 'CUST254511' 'CUST502630' 'CUST943170' 'CUST432711'
 'CUST371782' 'CUST452161' 'CUST668969' 'CUST468845' 'CUST812131'
 'CUST188025' 'CUST898207' 'CUST335113' 'CUST596564' 'CUST915573'
 'CUST720859' 'CUST549186' 'CUST766459' 'CUST556732' 'CUST497399'
 'CUST835244' 'CUST824156' 'CUST421080' 'CUST575786' 'CUST300845'
 'CUST410636' 'CUST831295' 'CUST153872' 'CUST950544' 'CUST913373'
 'CUST876039' 'CUST102805' 'CUST174637' 'CUST378535' 'CUST591465'
 'CUST870214' 'CUST961322' 'CUST765620' 'CUST827369' 'CUST639593'
 'CUST563513' 'CUST760626' 'CUST583863' 'CUST355570' 'CUST456385'
 'CUST664742' 'CUST344907' 'CUST232378' 'CUST261859' 'CUST757246'
 'CUST203225' 'CUST551607' 'CUST816318' 'CUST943718' 'CUST823846'
 'CUST410244' 'CUST940886' 'CUST134985' 'CUST483629' 'CUST178957'
 'CUST229592' 'CUST688678' 'CUST147549' 'CUST879238' 'CUST393328'
 'CUST670913' 'CUST772875' 'CUST714867' 'CUST937302' 'CUST282710'
 'CUST638169' 'CUST774591' 'CUST737846' 'CUST409222' 'CUST573489'
 'CUST367271' 'CUST951201' 'CUST886730' 'CUST788637' 'CUST986209'
 'CUST386544' 'CUST132146' 'CUST914571' 'CUST794093' 'CUST397005'
 'CUST416061' 'CUST498676' 'CUST582087' 'CUST121869' 'CUST519902'
 'CUST219565' 'CUST731661' 'CUST691912' 'CUST158900' 'CUST996840'
 'CUST783501' 'CUST629057' 'CUST396635' 'CUST199096' 'CUST466813'
 'CUST774751' 'CUST324597' 'CUST139581' 'CUST145814' 'CUST424500'
 'CUST538997' 'CUST845957' 'CUST956375' 'CUST335445' 'CUST829884'
 'CUST862560' 'CUST932463' 'CUST853448' 'CUST189772' 'CUST145649'
 'CUST208699' 'CUST829168' 'CUST430926' 'CUST918771' 'CUST295892'
 'CUST731718' 'CUST852524' 'CUST770532' 'CUST989894' 'CUST694799'
 'CUST484774' 'CUST688956' 'CUST242321' 'CUST676713' 'CUST930541'
 'CUST741674' 'CUST432427' 'CUST553633' 'CUST397846' 'CUST626986'
 'CUST965322' 'CUST131757' 'CUST176517' 'CUST869864' 'CUST571435'
 'CUST856157' 'CUST512344' 'CUST805188' 'CUST147440' 'CUST901535'
 'CUST483366' 'CUST579187' 'CUST452713' 'CUST214928' 'CUST856442'
 'CUST133104' 'CUST530311' 'CUST794395' 'CUST774558' 'CUST317346'
 'CUST958130' 'CUST311883' 'CUST153231' 'CUST908206' 'CUST777273']

--------------------------------------------
Column: channel
['Web Chat' 'Branch' 'Phone' 'Email' 'Mobile App']

--------------------------------------------
Column: category
['Fraud/Unauthorized' 'Loan' 'KYC' 'Account Access']

--------------------------------------------
Column: sub_category
["I see a transaction of ₹999 I didn't m"
 "I see a transaction of ₹500 I didn't m"
 "I see a transaction of ₹25000 I didn't m"
 "There's an ATM withdrawal of ₹5000 from"
 "There's an ATM withdrawal of ₹7500 from"
 "There's an ATM withdrawal of ₹2000 from"
 "There's an ATM withdrawal of ₹15000 from"
 "There's an ATM withdrawal of ₹500 from"
 'I received an OTP but never requested it'
 'My card was charged ₹999 by an unknown'
 'My card was charged ₹500 by an unknown'
 'My card was charged ₹25000 by an unknown'
 'My card was charged ₹15000 by an unknown'
 'I got a message that ₹15000 was debited '
 'I got a message that ₹7500 was debited '
 'I got a message that ₹3500 was debited '
 'I got a message that ₹1500 was debited '
 'I got a message that ₹25000 was debited '
 'Multiple small transactions from my acco'
 'Someone used my credit card online witho'
 'I found a duplicate charge of ₹999 on '
 'I found a duplicate charge of ₹25000 on '
 'I found a duplicate charge of ₹2000 on '
 'I found a duplicate charge of ₹7500 on '
 'I found a duplicate charge of ₹1500 on '
 'I never signed up for this subscription '
 'My UPI ID was used to transfer money wit'
 'What is the status of my home loan appli'
 'My personal loan was approved but I have'
 'Why was my loan application rejected'
 'I applied for a business loan 3 weeks ag'
 'Can I get an education loan for my child'
 'My EMI was deducted twice this month' 'I want to foreclose my car loan'
 'My loan top-up request has been pending '
 'Interest rate on my loan seems higher th'
 'I want to restructure my loan due to job'
 'My account is frozen because of KYC but '
 "I can't complete video KYC — the link ke"
 'Why is my KYC showing as incomplete even'
 'I updated my address but KYC is still sh'
 'My NRI account KYC is expiring next mont'
 'My company account KYC documents were su'
 "I can't link my Aadhaar due to name mism"
 'Why is my account marked as dormant'
 'My PAN verification is failing on net ba'
 'I need to update my mobile number for KY'
 "I'm unable to login to my net banking ac"
 'My account is showing negative balance b'
 "I forgot my ATM PIN and can't reset it o"
 'My salary credit is delayed by 3 days'
 'I need to close my account but there are'
 'My fixed deposit matured but amount not '
 'I want to add my wife as a joint account'
 'My cheque was returned even though I had'
 'Why was my NEFT transfer delayed'
 "I can't see my recent transactions in th"]

--------------------------------------------
Column: query_text
["I see a transaction of ₹999 I didn't make on 25-Apr-2023"
 "I see a transaction of ₹500 I didn't make on 16-Sep-2023"
 "I see a transaction of ₹25,000 I didn't make on 24-Dec-2023"
 "I see a transaction of ₹999 I didn't make on 16-May-2023"
 "I see a transaction of ₹25,000 I didn't make on 24-Jan-2023"
 "There's an ATM withdrawal of ₹5,000 from Bangalore but I'm in Ahmedabad"
 "There's an ATM withdrawal of ₹7,500 from Hyderabad but I'm in Chandigarh"
 "There's an ATM withdrawal of ₹2,000 from Hyderabad but I'm in Jaipur"
 "There's an ATM withdrawal of ₹15,000 from Hyderabad but I'm in Chandigarh"
 "There's an ATM withdrawal of ₹500 from Hyderabad but I'm in Ahmedabad"
 'I received an OTP but never requested it'
 'My card was charged ₹999 by an unknown merchant'
 'My card was charged ₹500 by an unknown merchant'
 'My card was charged ₹25,000 by an unknown merchant'
 'My card was charged ₹15,000 by an unknown merchant'
 "I got a message that ₹15,000 was debited but I didn't shop"
 "I got a message that ₹7,500 was debited but I didn't shop"
 "I got a message that ₹3,500 was debited but I didn't shop"
 "I got a message that ₹1,500 was debited but I didn't shop"
 "I got a message that ₹25,000 was debited but I didn't shop"
 "Multiple small transactions from my account I don't recognize"
 'Someone used my credit card online without my knowledge'
 'I found a duplicate charge of ₹999 on my statement'
 'I found a duplicate charge of ₹25,000 on my statement'
 'I found a duplicate charge of ₹2,000 on my statement'
 'I found a duplicate charge of ₹7,500 on my statement'
 'I found a duplicate charge of ₹1,500 on my statement'
 'I never signed up for this subscription but ₹5,000 is charged monthly'
 'I never signed up for this subscription but ₹25,000 is charged monthly'
 'I never signed up for this subscription but ₹999 is charged monthly'
 'I never signed up for this subscription but ₹500 is charged monthly'
 'My UPI ID was used to transfer money without my consent'
 'What is the status of my home loan application #TKT128276?'
 'What is the status of my home loan application #TKT497519?'
 'What is the status of my home loan application #TKT593152?'
 'What is the status of my home loan application #TKT979995?'
 'What is the status of my home loan application #TKT904150?'
 "My personal loan was approved but I haven't received the amount"
 'Why was my loan application rejected?'
 'I applied for a business loan 3 weeks ago and heard nothing'
 'Can I get an education loan for my child?'
 'My EMI was deducted twice this month' 'I want to foreclose my car loan'
 'My loan top-up request has been pending for 2 weeks'
 'Interest rate on my loan seems higher than agreed'
 'I want to restructure my loan due to job loss'
 'My account is frozen because of KYC but I submitted documents'
 "I can't complete video KYC — the link keeps failing"
 'Why is my KYC showing as incomplete even after Aadhaar update?'
 'I updated my address but KYC is still showing old address'
 'My NRI account KYC is expiring next month'
 'My company account KYC documents were submitted but account is still restricted'
 "I can't link my Aadhaar due to name mismatch"
 'Why is my account marked as dormant?'
 'My PAN verification is failing on net banking'
 'I need to update my mobile number for KYC'
 "I'm unable to login to my net banking account"
 "My account is showing negative balance but I didn't overdraw"
 "I forgot my ATM PIN and can't reset it online"
 'My salary credit is delayed by 3 days'
 'I need to close my account but there are pending charges'
 'My fixed deposit matured but amount not credited'
 'I want to add my wife as a joint account holder'
 'My cheque was returned even though I had sufficient balance'
 'Why was my NEFT transfer delayed?'
 "I can't see my recent transactions in the app"]

--------------------------------------------
Column: sentiment
['Urgent' 'Neutral' 'Confused' 'Frustrated' 'Angry' 'Anxious']

--------------------------------------------
Column: risk_level
['High' 'Medium' 'Low']

--------------------------------------------
Column: resolution_text
['Unauthorized transaction reported on account. Card blocked immediately. Dispute raised (Ref #TKT126225). Refund initiated within 7-10 working days after investigation.'
 'Unauthorized transaction reported on account. Card blocked immediately. Dispute raised (Ref #TKT131244). Refund initiated within 7-10 working days after investigation.'
 'Unauthorized transaction reported on account. Card blocked immediately. Dispute raised (Ref #TKT391704). Refund initiated within 7-10 working days after investigation.'
 'Unauthorized transaction reported on account. Card blocked immediately. Dispute raised (Ref #TKT476417). Refund initiated within 7-10 working days after investigation.'
 'Unauthorized transaction reported on account. Card blocked immediately. Dispute raised (Ref #TKT479201). Refund initiated within 7-10 working days after investigation.'
 'Location mismatch confirmed. ATM transaction flagged. Temporary hold placed on debit card. Branch visit requested with ID for card replacement.'
 'OTP triggered without user action — possible phishing or SIM swap attempt. Account access temporarily suspended. Customer advised to contact nearest branch.'
 'Merchant identified as third-party aggregator. Charge disputed. Provisional credit of ₹999 applied. Merchant notified for chargeback.'
 'Merchant identified as third-party aggregator. Charge disputed. Provisional credit of ₹500 applied. Merchant notified for chargeback.'
 'Merchant identified as third-party aggregator. Charge disputed. Provisional credit of ₹25,000 applied. Merchant notified for chargeback.'
 'Merchant identified as third-party aggregator. Charge disputed. Provisional credit of ₹15,000 applied. Merchant notified for chargeback.'
 'SMS alert verified in system. Transaction traced to recurring subscription. Customer advised to cancel subscription or raise dispute.'
 'Pattern of micro-transactions detected — possible card skimming. Card blocked. New card dispatched. FIR lodged on behalf of customer.'
 'Card-not-present fraud detected. Credit card blocked. Dispute filed. Refund processed in 5-7 days after merchant response.'
 'Duplicate charge confirmed by payment processor. Full refund credited to account within 3 business days.'
 'Recurring mandate identified. Mandate cancelled. Last 3 months of charges refunded. Customer informed of opt-out process.'
 'UPI transaction flagged. Complaint raised with NPCI. Account temporarily restricted. Customer advised to change UPI PIN immediately.'
 'Loan application #TKT128276 is under credit appraisal. Verification of property documents pending. Expected decision within 5 working days.'
 'Loan application #TKT497519 is under credit appraisal. Verification of property documents pending. Expected decision within 5 working days.'
 'Loan application #TKT593152 is under credit appraisal. Verification of property documents pending. Expected decision within 5 working days.'
 'Loan application #TKT979995 is under credit appraisal. Verification of property documents pending. Expected decision within 5 working days.'
 'Loan application #TKT904150 is under credit appraisal. Verification of property documents pending. Expected decision within 5 working days.'
 'Loan disbursement scheduled. Delay due to NACH mandate registration. Amount to be credited within 48 hours.'
 'Application reviewed. Rejection due to low CIBIL score (540). Recommended: clear existing dues, re-apply after 6 months.'
 'Application reviewed. Rejection due to low CIBIL score (634). Recommended: clear existing dues, re-apply after 6 months.'
 'Application reviewed. Rejection due to low CIBIL score (525). Recommended: clear existing dues, re-apply after 6 months.'
 'Application reviewed. Rejection due to low CIBIL score (640). Recommended: clear existing dues, re-apply after 6 months.'
 'Application reviewed. Rejection due to low CIBIL score (480). Recommended: clear existing dues, re-apply after 6 months.'
 'Application under enhanced due diligence. Additional documents requested via email. Please submit GST returns for last 2 years.'
 'Education loan schemes available for recognized institutions. Loan up to ₹20L for domestic courses. Connect to nearest branch for application.'
 'Duplicate EMI deduction confirmed. Extra amount of ₹15,000 to be refunded within 3 working days.'
 'Duplicate EMI deduction confirmed. Extra amount of ₹2,000 to be refunded within 3 working days.'
 'Duplicate EMI deduction confirmed. Extra amount of ₹5,000 to be refunded within 3 working days.'
 'Duplicate EMI deduction confirmed. Extra amount of ₹10,000 to be refunded within 3 working days.'
 'Foreclosure request received. Outstanding principal: ₹500. Foreclosure charges: 2% of outstanding. No-dues certificate issued upon full payment.'
 'Foreclosure request received. Outstanding principal: ₹3,500. Foreclosure charges: 2% of outstanding. No-dues certificate issued upon full payment.'
 'Foreclosure request received. Outstanding principal: ₹15,000. Foreclosure charges: 2% of outstanding. No-dues certificate issued upon full payment.'
 'Foreclosure request received. Outstanding principal: ₹25,000. Foreclosure charges: 2% of outstanding. No-dues certificate issued upon full payment.'
 'Top-up application under review. Income documents pending verification. Customer to submit latest 3-month salary slips.'
 'Loan agreement reviewed. Rate of interest matches agreed terms. Variation due to MCLR reset — customer informed as per RBI guidelines.'
 'Moratorium request initiated under RBI COVID restructuring guidelines. EMI holiday of 3 months granted. Interest capitalised during moratorium period.'
 'Documents received but not yet verified. Account unfreezing expected within 48 hours. Customer to re-submit Aadhaar and PAN via net banking portal.'

In [9]:
support_tickets["amt"] = (
    support_tickets["query_text"]
    .str.extract(r"₹([\d,]+)")[0]
    .str.replace(",", "", regex=False)
)

support_tickets["sub_category"] = support_tickets.apply(
    lambda row: row["sub_category"].replace("{amt}", row["amt"])
    if pd.notna(row["amt"]) else row["sub_category"],
    axis=1
)

support_tickets = support_tickets.drop(columns=["amt"])

support_tickets

,ticket_id,date_created,customer_id,channel,category,sub_category,query_text,sentiment,risk_level,resolution_text,resolution_time_minutes,resolved_by,customer_satisfaction,escalated
0,TKT-10001,2023-03-13,CUST872246,Web Chat,Fraud/Unauthorized,I see a transaction of ₹999 I didn't m,I see a transaction of ₹999 I didn't make on 2...,Urgent,High,Unauthorized transaction reported on account. ...,28,Sneha R.,2,Yes
1,TKT-10002,2023-11-05,CUST127824,Branch,Fraud/Unauthorized,I see a transaction of ₹500 I didn't m,I see a transaction of ₹500 I didn't make on 1...,Neutral,High,Unauthorized transaction reported on account. ...,27,Auto-Resolved,5,No
2,TKT-10003,2023-08-05,CUST456778,Phone,Fraud/Unauthorized,I see a transaction of ₹25000 I didn't m,"I see a transaction of ₹25,000 I didn't make o...",Neutral,High,Unauthorized transaction reported on account. ...,11,Anjali K.,2,No
3,TKT-10004,2023-01-23,CUST865179,Email,Fraud/Unauthorized,I see a transaction of ₹999 I didn't m,I see a transaction of ₹999 I didn't make on 1...,Confused,High,Unauthorized transaction reported on account. ...,8,Vikram P.,2,Yes
4,TKT-10005,2023-12-05,CUST338968,Phone,Fraud/Unauthorized,I see a transaction of ₹25000 I didn't m,"I see a transaction of ₹25,000 I didn't make o...",Frustrated,High,Unauthorized transaction reported on account. ...,12,Priya S.,5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,TKT-10196,2023-07-22,CUST958130,Phone,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Neutral,Low,App sync issue identified. Cache cleared from ...,104,Priya S.,4,No
196,TKT-10197,2023-04-20,CUST311883,Branch,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Anxious,Low,App sync issue identified. Cache cleared from ...,173,Auto-Resolved,4,No
197,TKT-10198,2023-05-05,CUST153231,Branch,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Neutral,Low,App sync issue identified. Cache cleared from ...,193,Rahul M.,3,No
198,TKT-10199,2023-12-15,CUST908206,Mobile App,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Frustrated,Low,App sync issue identified. Cache cleared from ...,170,Rahul M.,4,No
199,TKT-10200,2023-05-27,CUST777273,Web Chat,Account Access,I can't see my recent transactions in th,I can't see my recent transactions in the app,Frustrated,Low,App sync issue identified. Cache cleared from ...,196,Sneha R.,3,No

In [10]:
transactions.loc[transactions["fraud_label"] == 0, "fraud_reason"] = "Not applicable"
transactions

,transaction_id,account_id,timestamp,amount_inr,merchant_name,merchant_category,transaction_type,city,hour_of_day,day_of_week,is_international,velocity_flag,geo_anomaly_flag,high_amount_flag,fraud_label,fraud_reason
0,TXN500001,ACC995993,2023-05-21 01:35:00,7553.61,Flipkart,E-commerce,Credit Card,Mumbai,1,Sunday,No,No,No,No,0,Not applicable
1,TXN500002,ACC163182,2023-09-26 10:44:00,634.78,Zomato,Food Delivery,Credit Card,Chennai,10,Tuesday,No,No,No,No,0,Not applicable
2,TXN500003,ACC107161,2023-08-26 01:35:00,1136.71,Zomato,Food Delivery,UPI,Hyderabad,1,Saturday,No,No,No,No,0,Not applicable
3,TXN500004,ACC103642,2023-07-09 02:34:00,41478.01,VPN_Service_Anon,Digital,UPI,Dubai,2,Sunday,Yes,Yes,Yes,Yes,1,Off-hours
4,TXN500005,ACC218118,2023-04-07 18:46:00,1139.76,Ola Cabs,Transport,Debit Card,Chennai,18,Friday,No,No,No,No,0,Not applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,TXN501996,ACC535604,2023-02-26 04:52:00,7815.03,Ola Cabs,Transport,Debit Card,Ahmedabad,4,Sunday,No,No,No,No,0,Not applicable
1996,TXN501997,ACC536045,2023-06-13 22:01:00,1566.37,Flipkart,E-commerce,Debit Card,Delhi,22,Tuesday,No,No,No,No,0,Not applicable
1997,TXN501998,ACC645617,2023-08-12 21:23:00,13608.73,MakeMyTrip,Travel,Credit Card,Mumbai,21,Saturday,No,No,No,No,0,Not applicable
1998,TXN501999,ACC133782,2023-10-18 14:54:00,317.03,MakeMyTrip,Travel,UPI,Ahmedabad,14,Wednesday,No,No,No,No,0,Not applicable
1999,TXN502000,ACC876513,2023-03-10 02:18:00,1689.71,PhonePe Wallet,Wallet,Net Banking,Chennai,2,Friday,No,No,No,No,0,Not applicable

In [11]:
support_tickets.to_csv("./dataset/support_tickets.csv", index=False)
transactions.to_csv("./dataset/transactions.csv", index=False)